/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function isValidMove(epd: string, moveFrom: string, moveTo: string): boolean
export declare function allPossibleMoves(epd: string, moveStr: string): string
export declare function nothingFn(): number
